# Generated by Django 4.2.7 on 2024-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['items']},
        ),
        migrations.AlterField(
            model_name='items',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
