# Generated by Django 4.2 on 2024-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
            ],
        ),
    ]
