# Generated by Django 4.2 on 2024-04-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCrud', '0002_searitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearItem',
            new_name='SearchItem',
        ),
    ]
