# Generated by Django 4.2.7 on 2024-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCrud', '0005_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
